version: 2

sources:
  - name: "{{ env_var('DB_NAME') }}"
    schema: public
    tables:
      - name: commune
      - name: departement
      - name: region
      - name: lycee
      - name: clubs_boxe_thai
      - name: ehpad
      - name: mairie
      - name: pharmacie
      - name: bibliotheque
      - name: college
